### ISSUE TITLE
unzip: command not found

### ISSUE THREAD

**Issue by morion4000** [nhumrich/step-deploy-to-rancher#1]
Getting:

2016-10-11 14:12:56 (97.4 MB/s) - 'file.zip' saved [442/442]

/pipeline/deploy-to-rancher-9d642872-7b8e-40e1-93bc-57d96fbf2872/run.sh: line 40: unzip: command not found
sed: can't read docker-compose.yml: No such file or directory
sed: can't read docker-compose.yml: No such file or directory
sed: can't read rancher-compose.yml: No such file or directory
sed: can't read docker-compose.yml: No such file or directory

**Comment by morion4000** [comment]
Using https://gist.github.com/morion4000/74bbe7803cdbe6546a87afe7c3128ac7

**Comment by nhumrich** [comment]
youll have to install `unzip` on the image.

**Comment by morion4000** [comment]
@nhumrich I did that in https://gist.github.com/morion4000/74bbe7803cdbe6546a87afe7c3128ac7#file-werker-yml-L6

**Comment by nhumrich** [comment]
What you install during the build wont still be there for another pipeline

Wercker only copies over what is in `/pipeline/source`, not the entire container

**Comment by morion4000** [comment]
Got it. Thank you.
