### ISSUE TITLE
sed: -e expression #1, char 53: unknown option to `s'

### ISSUE THREAD

**Issue by Wotre** [nhumrich/step-deploy-to-rancher#2]
--2017-01-08 13:56:29--  https://*hidden*:*password*@*hidden*/v1/environments/1e41/composeconfig
Resolving *hidden* (*hidden*)... *hidden*
Connecting to *hidden* (*hidden*)|*hidden*|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Reusing existing connection to *hidden*:443.
HTTP request sent, awaiting response... 200 OK
Length: 501 [application/zip]
Saving to: 'file.zip'

     0K                                                       100% 6.01M=0s

2017-01-08 13:56:30 (6.01 MB/s) - 'file.zip' saved [501/501]

Archive:  file.zip
  inflating: docker-compose.yml      
  inflating: rancher-compose.yml     
sed: -e expression #1, char 53: unknown option to `s'

**Comment by nhumrich** [comment]
If you expect me to do anything about this youll have to provide more information. This is just the output. I have no idea what your input is. Maybe there is an edge case as to what the service name is. Or maybe your sed version is old or non-gnu. 
So maybe you could provide `sed --version` as well as your inputs (other than the keys).

**Comment by Wotre** [comment]
My apologies, been quite a while since my original post.

The above issue was caused due to a forward slash (/) in my docker_org. I'm using a private registry, and my image is in a format like this: registry_url.com/organisation/image:latest. I originally entered registry_url.com/organisation as the docker_org. I've now escaped the / (so it's now registry_url.com\/organisation).

I've now stumbled upon another error sadly, resulting in this error message:
rancher-compose --url https://registry_url.com/v1 --access-key xxxx --secret-key xxxx --project-name xxx upgrade  xxx-15618 --pull --update-links -c --interval 30000
time="2017-01-29T23:34:47Z" level=fatal msg="Failed to read project: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into map[string]interface {}"

I am using v1 of the rancher API as the rancher_url (so: https://rancher_url/v1). In v2 of the api the /environments call that's being used doesn't exist anymore. In the downloaded rancher-compose.yml the first line is this though: "version: '2'". I think the included rancher-compose (or the v1 rancher url) doesn't play nice with a v2 rancher-compose.

Any plans for version 2 support?

**Comment by nhumrich** [comment]
I actually use a different script now that uses some of the newer concepts like upgrading in place. It requires python and I run it in its own container. Once v2 is out of beta, I will probably support it. I will try to clean it up and open source it for you.

**Comment by Wotre** [comment]
That would certainly be appreciated, thanks in advance!

**Comment by nhumrich** [comment]
And here ya go. https://github.com/nhumrich/deploy-to-rancher
Feel free to add an issue to the new repo for api v2 support.
